[SRE-1843] Fix error when no more healthy seeds
bukalapak/redis-cluster pull request #13
Opened 2020-01-14 11:09 UTC by imamfzn

There a bug on redis-cluster client when no healthy seed when reset connection to redis-cluster.

The error is:
```
no implicit conversion from nil to integer (TypeError)
from /mothership/vendor/bundle/ruby/2.3.0/bundler/gems/redis-cluster-8875e0b948eb/lib/redis_cluster/cluster.rb:89:in `rescue in reset'
```
It caused by when no healthy seed,  var i on https://github.com/bukalapak/redis-cluster/blob/fix/lib/redis_cluster/cluster.rb#L83-L89 not declared / nil.

2020-01-14 11:44 UTC, IndraGunawan requested changes

2020-01-14 11:44 UTC, IndraGunawan commented on lib/redis_cluster/cluster.rb
> +      rescue NoHealthySeedError => e
gak perlu di re-raise kalau tidak ada penanganan khusus ketika terjadi error

2020-01-14 11:44 UTC, IndraGunawan commented on lib/redis_cluster/cluster.rb
> +  class NoHealthySeedError < StandardError; end
sepertinya defenisi ini ada di file lib/redis_cluster.rb karena kalau dilihat ini class yang ada didalam class RedisCluster bukan di Cluster, wdyt?

2020-01-14 11:44 UTC, IndraGunawan commented on lib/redis_cluster/cluster.rb
> +        raise NO_HEALTHY_SEED_ERROR if pool.length.zero?
jumlah element dari `pool` nya bisa berubah setiap iterasi?

2020-01-14 11:51 UTC, imamfzn commented on lib/redis_cluster/cluster.rb
> +      rescue NoHealthySeedError => e
Kalau gak gini karena bakal masuk ke rescue yang `StandardError`, karena `NoHealthyError`  intherit dari `StandardError`

2020-01-14 11:52 UTC, imamfzn commented on lib/redis_cluster/cluster.rb
> +        raise NO_HEALTHY_SEED_ERROR if pool.length.zero?
pool nya cuma di set diatas sblm begin

2020-01-14 11:53 UTC, imamfzn commented on lib/redis_cluster/cluster.rb
> +  class NoHealthySeedError < StandardError; end
saya ngikutin definisi yang di `https://github.com/bukalapak/redis-cluster/blob/fix/lib/redis_cluster/client.rb#L10` . dan si `NoHealthyError` ini cuma dipake dii file ini aja kayak di referensi sblmnya.

2020-01-14 11:58 UTC, IndraGunawan approved these changes

2020-01-15 04:01 UTC, rolandhawk approved these changes

2020-01-15 08:52 UTC, ardfard approved these changes

2020-02-03 05:36 UTC, merged